version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  node_app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  # angular_app:
  #   depends_on:
  #     - node_app
  #   build: .
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT
  #   # environment:
  #   #   - DB_HOST=mysqldb
  #   #   - DB_USER=$MYSQLDB_USER
  #   #   - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #   #   - DB_NAME=$MYSQLDB_DATABASE
  #   #   - DB_PORT=$MYSQLDB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true

volumes: 
  db: